version: "3.3"

volumes:
  mysql-volume:
  mongo-volume:

services:
  core:
    image: taktakty/core:latest
    build:
      context: core
      target: development
    container_name: core
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - mysql
    volumes:
      - ./core/src:/app/src
    env_file:
      - .env

  grpcserver:
    image: taktakty/grpcserver:latest
    build:
      context: grpcserver
      target: development
    container_name: grpcserver
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    volumes:
      - ./grpcserver:/app

  mongo:
    image: mongo:3.6.21
    container_name: mongo
    volumes:
      - mongo-volume:/data/db
    ports:
      - "27017:27017"

  mysql:
    image: mysql:5.7.32
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=dev1234
      - MYSQL_DATABASE=development
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=dev1234
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306
