# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculate_proto/room.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculate_proto/room.proto',
  package='room',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1a\x63\x61lculate_proto/room.proto\x12\x04room\x1a\x1bgoogle/protobuf/empty.proto\".\n\x04Room\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04user\x18\x03 \x01(\t\"\x11\n\x0fRoomListRequest\"!\n\x13RoomRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\t2\xed\x01\n\x0eRoomController\x12-\n\x04List\x12\x15.room.RoomListRequest\x1a\n.room.Room\"\x00\x30\x01\x12\"\n\x06\x43reate\x12\n.room.Room\x1a\n.room.Room\"\x00\x12\x33\n\x08Retrieve\x12\x19.room.RoomRetrieveRequest\x1a\n.room.Room\"\x00\x12\"\n\x06Update\x12\n.room.Room\x1a\n.room.Room\"\x00\x12/\n\x07\x44\x65stroy\x12\n.room.Room\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_ROOM = _descriptor.Descriptor(
  name='Room',
  full_name='room.Room',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='room.Room.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='room.Room.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user', full_name='room.Room.user', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=111,
)


_ROOMLISTREQUEST = _descriptor.Descriptor(
  name='RoomListRequest',
  full_name='room.RoomListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=130,
)


_ROOMRETRIEVEREQUEST = _descriptor.Descriptor(
  name='RoomRetrieveRequest',
  full_name='room.RoomRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='room.RoomRetrieveRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=165,
)

DESCRIPTOR.message_types_by_name['Room'] = _ROOM
DESCRIPTOR.message_types_by_name['RoomListRequest'] = _ROOMLISTREQUEST
DESCRIPTOR.message_types_by_name['RoomRetrieveRequest'] = _ROOMRETRIEVEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Room = _reflection.GeneratedProtocolMessageType('Room', (_message.Message,), {
  'DESCRIPTOR' : _ROOM,
  '__module__' : 'calculate_proto.room_pb2'
  # @@protoc_insertion_point(class_scope:room.Room)
  })
_sym_db.RegisterMessage(Room)

RoomListRequest = _reflection.GeneratedProtocolMessageType('RoomListRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROOMLISTREQUEST,
  '__module__' : 'calculate_proto.room_pb2'
  # @@protoc_insertion_point(class_scope:room.RoomListRequest)
  })
_sym_db.RegisterMessage(RoomListRequest)

RoomRetrieveRequest = _reflection.GeneratedProtocolMessageType('RoomRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROOMRETRIEVEREQUEST,
  '__module__' : 'calculate_proto.room_pb2'
  # @@protoc_insertion_point(class_scope:room.RoomRetrieveRequest)
  })
_sym_db.RegisterMessage(RoomRetrieveRequest)



_ROOMCONTROLLER = _descriptor.ServiceDescriptor(
  name='RoomController',
  full_name='room.RoomController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=168,
  serialized_end=405,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='room.RoomController.List',
    index=0,
    containing_service=None,
    input_type=_ROOMLISTREQUEST,
    output_type=_ROOM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='room.RoomController.Create',
    index=1,
    containing_service=None,
    input_type=_ROOM,
    output_type=_ROOM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Retrieve',
    full_name='room.RoomController.Retrieve',
    index=2,
    containing_service=None,
    input_type=_ROOMRETRIEVEREQUEST,
    output_type=_ROOM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='room.RoomController.Update',
    index=3,
    containing_service=None,
    input_type=_ROOM,
    output_type=_ROOM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Destroy',
    full_name='room.RoomController.Destroy',
    index=4,
    containing_service=None,
    input_type=_ROOM,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROOMCONTROLLER)

DESCRIPTOR.services_by_name['RoomController'] = _ROOMCONTROLLER

# @@protoc_insertion_point(module_scope)
